[tool.poetry]
name = "repl_python3_project-euler-solutions"
version = "0.1.0"
description = ""
authors = ["mon-neutrino <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
sympy = "^1.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
